#include <iostream>
using namespace std;

/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

int maxfiboval = 4000000;
int answer() {
   int val = 0;
   int *arr;
   arr = &val;
   int sum = 2;
   *arr = 1;
   arr++;
   *arr= 2;
   int subsum = 0;
   while(true) {
     subsum = *arr;
     --arr;
     subsum += *arr;
     arr += 2;
     *arr = subsum;
     if (*arr < maxfiboval) {
         if (*arr % 2 == 0)
             sum += *arr;
     }
     else {
       break;
     }
     --arr;
     subsum = *arr;
     --arr;
     *arr = subsum;
     arr += 2;
     subsum = *arr;
     --arr;
     *arr = subsum;
   }
   return sum;
}

int main()
{
    cout << answer() << "\n";
}
